---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: freeipa
  labels:
    app: freeipa
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list", "get"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get", "watch", "delete", "create"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["list", "get", "patch", "delete", "create"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "delete", "create"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["delete", "create"]
  - apiGroups: ["route.openshift.io"]
    resources: ["routes", "routes/custom-host"]
    verbs: ["create", "delete"]
