# https://github.com/marketplace/actions/hadolint-action
name: Lint Dockerfile

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile

